# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0002_remove_info_wind_deg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='weather_desciption',
            new_name='weather_description',
        ),
    ]
